name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck build-essential cmake
        
    - name: Run cppcheck
      run: |
        cppcheck --enable=all --std=c99 --platform=unix64 \
                 --suppress=missingIncludeSystem \
                 --suppress=unusedFunction \
                 --error-exitcode=1 \
                 --inline-suppr \
                 -I include/ \
                 src/ main.c
                 
    - name: Check code formatting (optional)
      run: |
        echo "Checking C code style..."
        # Add clang-format check if needed
        
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure project
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        
    - name: Build project
      run: |
        cmake --build build
        
    - name: List generated files
      run: |
        ls -la build/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: calculadora-build
        path: build/calculadora
        
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure and build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build
        
    - name: Run tests
      run: |
        cd build
        # Add test execution here when tests are available
        echo "Tests would run here"
        
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    needs: lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
      
    - name: Configure project
      run: |
        cmake -B build -G "Visual Studio 17 2022"
        
    - name: Build project
      run: |
        cmake --build build --config Release
        
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: calculadora-windows
        path: build/bin/Release/calculadora.exe
